// Web/React/src/AliAIChat/Call/Footer.vue
<script lang="ts">
import { computed, defineComponent } from 'vue'
import { AICallAgentType, AICallState } from 'aliyun-auikit-aicall'
import { isMobile } from '../common/utils'
import Icons from './Icons.vue'
import useCallStore from './store'
import { useController } from './hooks/use-controller'

export default defineComponent({
  name: 'CallFooter',
  components: {
    Icons,
  },
  emits: ['call', 'stop'],
  setup(_, { emit }) {
    const { controllerRef: controller } = useController()

    const {
      agentType,
      callState,
      microphoneMuted,
      cameraMuted,
      pushingToTalk,
      enablePushToTalk,
    } = storeToRefs(useCallStore())

    let pushingStartTime = 0
    let pushingTimer: number | null = null
    const isTouchSupported = 'ontouchstart' in window

    const isVisionAgentAndConnected = computed(
      () =>
        agentType.value === AICallAgentType.VisionAgent
        && callState.value === AICallState.Connected,
    )

    const needEmptyBtn = computed(
      () =>
        callState.value === AICallState.Connected
        && agentType.value !== AICallAgentType.VisionAgent
        && enablePushToTalk.value,
    )

    const toggleMicrophoneMuted = (e: Event) => {
      e.stopPropagation()
      if (enablePushToTalk.value)
        return
      const to = !microphoneMuted.value
      if (controller) {
        controller.value.muteMicrophone(to)
      }
      microphoneMuted.value = to
    }

    const toggleCameraMuted = (e: Event) => {
      e.stopPropagation()
      const to = !cameraMuted.value
      if (controller) {
        controller.value.muteCamera(to)
      }
      cameraMuted.value = to
    }

    const switchCamera = (e: Event) => {
      e.stopPropagation()
      if (controller) {
        controller.value.switchCamera()
      }
    }

    const stopPushToTalk = () => {
      if (!pushingStartTime || !enablePushToTalk.value)
        return
      if (pushingTimer) {
        clearTimeout(pushingTimer)
        pushingTimer = null
      }
      const duration = Date.now() - pushingStartTime
      if (duration < 500) {
        ElMessage.error('说话时间太短')
        if (controller) {
          controller.value.cancelPushToTalk()
        }
      }
      else {
        if (controller) {
          controller.value.finishPushToTalk()
        }
      }
      pushingToTalk.value = false
      pushingStartTime = 0
    }

    const startPushToTalk = () => {
      if (!enablePushToTalk.value)
        return
      if (controller) {
        controller.value.startPushToTalk()
      }
      pushingToTalk.value = true
      pushingStartTime = Date.now()
      pushingTimer = window.setTimeout(() => {
        stopPushToTalk()
      }, 60 * 1000)
    }

    const onCallClick = (e: Event) => {
      e.stopPropagation()
      if (
        callState.value === AICallState.Connected
        || callState.value === AICallState.Connecting
      ) {
        onStop()
      }
      else {
        onCall()
      }
    }

    function onCall() {
      emit('call')
    }

    function onStop() {
      emit('stop')
    }

    return {
      agentType,
      callState,
      microphoneMuted,
      cameraMuted,
      enablePushToTalk,
      pushingToTalk,
      isTouchSupported,
      isVisionAgentAndConnected,
      needEmptyBtn,
      toggleMicrophoneMuted,
      toggleCameraMuted,
      switchCamera,
      stopPushToTalk,
      startPushToTalk,
      onCallClick,
      isMobile,
      AICallAgentType,
      AICallState,
    }
  },
})
</script>

<template>
  <div class="call-footer">
    <ul class="_action-list">
      <!-- 视觉模式下的摄像头按钮 -->
      <li v-if="isVisionAgentAndConnected" key="camera" class="_camera">
        <div v-if="!cameraMuted && isMobile" class="_camera-switch">
          <el-button @click="switchCamera">
            <Icons name="CameraSwitchSVG" />
          </el-button>
          <div class="_label">
            镜头翻转
          </div>
        </div>
        <el-button @click="toggleCameraMuted">
          <Icons :name="cameraMuted ? 'CameraClosedSVG' : 'CameraSVG'" />
        </el-button>
        <div class="_label">
          {{ cameraMuted ? '摄像头已关' : '关摄像头' }}
        </div>
      </li>

      <!-- 通话按钮，在非对讲机模式下位于中间 -->
      <li
        key="call"
        class="_call"
        :class="{
          'is-connected':
            callState === AICallState.Connected
            || callState === AICallState.Connecting,
        }"
      >
        <el-button @click="onCallClick">
          <Icons name="CallPhoneSVG" />
        </el-button>
        <div class="_label">
          {{
            callState === AICallState.Connected
              || callState === AICallState.Connecting
              ? '挂断'
              : '拨打'
          }}
        </div>
      </li>

      <!-- 麦克风按钮，在对讲机模式下位于中间 -->
      <li
        v-if="callState === AICallState.Connected"
        key="microphone"
        class="_microphone"
        :class="{ 'is-push-to-talk': enablePushToTalk }"
        @contextmenu.prevent
      >
        <el-button
          :class="{ 'is-pushing': pushingToTalk }"
          @touchstart="startPushToTalk"
          @touchend="stopPushToTalk"
          @mousedown="!isTouchSupported ? startPushToTalk : undefined"
          @mouseup="!isTouchSupported ? stopPushToTalk : undefined"
          @click="toggleMicrophoneMuted"
        >
          <Icons :name="microphoneMuted ? 'MicrophoneClosedSVG' : 'MicrophoneSVG'" />
        </el-button>

        <div class="_label">
          <template v-if="enablePushToTalk">
            {{ pushingToTalk ? '松开发送' : '按住讲话' }}
          </template>
          <template v-else>
            {{ microphoneMuted ? '麦克风已关' : '关麦克风' }}
          </template>
        </div>
      </li>

      <!-- 占位元素，保持布局 -->
      <li v-if="needEmptyBtn" key="empty" />
    </ul>
  </div>
</template>

<style lang="scss">
.call-footer {
  position: relative;
  z-index: 3;
  height: 126px;
  text-align: center;
  user-select: none;

  ._action-list {
    display: flex;
    justify-content: center;
    list-style: none;
    margin: 0;
    padding: 0;

    li {
      position: relative;
      margin: 0 10px;
      width: 52px;
      padding-bottom: 40px;
    }

    .el-button {
      width: 40px;
      height: 40px;
      border-radius: 20px;
      border-color: #d8d9e6;
      padding: 0;
    }

    ._camera-switch {
      position: absolute;
      border: none;
      top: 0;
      left: -60px;
      padding-bottom: 40px;
      .el-button {
        border: none;
        background: none !important;
      }
    }

    ._label {
      position: absolute;
      bottom: 0;
      margin-top: 8px;
      font-size: 12px;
      line-height: 32px;
      color: #878aab;
      white-space: nowrap;
      left: 50%;
      transform: translate3d(-50%, 0, 0);
    }

    ._call {
      .el-button {
        background: #20c591;
        border-color: #20c591;
        transition: background ease-in-out 200ms;
        & > span {
          transform: rotate(-130deg);
          transition: transform ease-in-out 200ms;
        }

        svg {
          margin-top: -3px;
        }
      }

      &.is-connected {
        .el-button {
          background: #f23139;
          border-color: #f23139;
          & > span {
            transform: rotate(0);
          }
        }
      }
    }

    ._microphone.is-push-to-talk {
      width: 82px;
      .el-button {
        width: 70px;
        &::before {
          display: none;
        }
        &.is-pushing {
          background: var(--adm-color-primary);
          color: #fff;
        }
      }
    }
  }
}
</style>

// Web/React/src/Mobile/Call/Footer.tsx
import { ReactNode, useContext, useMemo, useRef } from 'react';
import { Button, Toast } from 'antd-mobile';
import { AICallAgentType, AICallState } from 'aliyun-auikit-aicall';

import ControllerContext from '@/Mobile/Call/ControlerContext';
import useCallStore from '@/Mobile/Call/store';
import {
  CallPhoneSVG,
  CameraClosedSVG,
  CameraSVG,
  CameraSwitchSVG,
  MicrophoneClosedSVG,
  MicrophoneSVG,
} from './Icons';

import './footer.less';
import { getRootElement, isMobile } from '@/common/utils';

interface CallFooterProps {
  onCall: () => void;
  onStop: () => void;
}

function Footer({ onStop, onCall }: CallFooterProps) {
  const controller = useContext(ControllerContext);
  const agentType = useCallStore((state) => state.agentType);
  const callState = useCallStore((state) => state.callState);
  const microphoneMuted = useCallStore((state) => state.microphoneMuted);
  const cameraMuted = useCallStore((state) => state.cameraMuted);
  const enablePushToTalk = useCallStore((state) => state.enablePushToTalk);
  const pushingToTalk = useCallStore((state) => state.pushingToTalk);
  const pushingStartTimeRef = useRef(0);
  const pushingTimerRef = useRef(0);
  const isTouchSupported = 'ontouchstart' in window;

  const toggleMicrophoneMuted = (
    e: React.MouseEvent<HTMLButtonElement, MouseEvent>,
  ) => {
    e.stopPropagation();
    if (enablePushToTalk) return;
    const to = !useCallStore.getState().microphoneMuted;
    controller?.muteMicrophone(to);
    // messageApi.success(to ? '麦克风已关闭' : '麦克风已开启');
    useCallStore.setState({
      microphoneMuted: to,
    });
  };

  const toggleCameraMuted = (
    e: React.MouseEvent<HTMLButtonElement, MouseEvent>,
  ) => {
    e.stopPropagation();
    const to = !useCallStore.getState().cameraMuted;
    controller?.muteCamera(to);
    // messageApi.success(to ? '摄像头已关闭' : '摄像头已开启');
    useCallStore.setState({
      cameraMuted: to,
    });
  };
  const switchCamera = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    e.stopPropagation();
    controller?.switchCamera();
  };

  const stopPushToTalk = useMemo(
    () => () => {
      if (
        !pushingStartTimeRef.current ||
        !useCallStore.getState().enablePushToTalk
      )
        return;
      if (pushingTimerRef.current) {
        clearTimeout(pushingTimerRef.current);
      }
      const duration = Date.now() - pushingStartTimeRef.current;
      if (duration < 500) {
        Toast.show({
          content: '说话时间太短',
          getContainer: () => getRootElement(),
        });
        controller?.cancelPushToTalk();
      } else {
        controller?.finishPushToTalk();
      }
      useCallStore.setState({
        pushingToTalk: false,
      });
      pushingStartTimeRef.current = 0;
    },
    [controller],
  );

  const startPushToTalk = useMemo(
    () => () => {
      if (!useCallStore.getState().enablePushToTalk) return;
      controller?.startPushToTalk();
      useCallStore.setState({
        pushingToTalk: true,
      });
      pushingStartTimeRef.current = Date.now();
      pushingTimerRef.current = window.setTimeout(() => {
        stopPushToTalk();
      }, 60 * 1000);
    },
    [controller, stopPushToTalk],
  );

  const onCallClick = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    e.stopPropagation();
    if (
      callState === AICallState.Connected ||
      callState === AICallState.Connecting
    ) {
      onStop();
    } else {
      onCall();
    }
  };

  const btns: ReactNode[] = [];

  const callBtn = (
    <li
      key='call'
      className={`_call ${
        callState === AICallState.Connected ||
        callState === AICallState.Connecting
          ? 'is-connected'
          : ''
      }`}
    >
      <Button onClick={onCallClick}>{CallPhoneSVG}</Button>
      <div className='_label'>
        {callState === AICallState.Connected ||
        callState === AICallState.Connecting
          ? '挂断'
          : '拨打'}
      </div>
    </li>
  );

  const emptyBtn = <li key='empty'></li>;

  if (callState === AICallState.Connected) {
    const microphoneBtn = (
      <li
        key='microphone'
        className={`_microphone ${enablePushToTalk ? 'is-push-to-talk' : ''}`}
        onContextMenu={(e) => e.preventDefault()}
      >
        <Button
          onTouchStart={startPushToTalk}
          onTouchEnd={stopPushToTalk}
          onMouseDown={!isTouchSupported ? startPushToTalk : undefined}
          onMouseUp={!isTouchSupported ? stopPushToTalk : undefined}
          onClick={toggleMicrophoneMuted}
          className={pushingToTalk ? 'is-pushing' : ''}
        >
          {microphoneMuted ? MicrophoneClosedSVG : MicrophoneSVG}
        </Button>

        {enablePushToTalk ? (
          <div className='_label'>
            {pushingToTalk ? '松开发送' : '按住讲话'}
          </div>
        ) : (
          <div className='_label'>
            {microphoneMuted ? '麦克风已关' : '关麦克风'}
          </div>
        )}
      </li>
    );

    if (agentType === AICallAgentType.VisionAgent) {
      const cameraBtn = (
        <li key='camera' className='_camera'>
          {!cameraMuted && isMobile() && (
            <div className='_camera-switch'>
              <Button onClick={switchCamera}>{CameraSwitchSVG}</Button>
              <div className='_label'>镜头翻转</div>
            </div>
          )}
          <Button onClick={toggleCameraMuted}>
            {cameraMuted ? CameraClosedSVG : CameraSVG}
          </Button>
          <div className='_label'>
            {cameraMuted ? '摄像头已关' : '关摄像头'}
          </div>
        </li>
      );
      btns.push(cameraBtn);

      // 对讲机模式，按钮在中间
      if (enablePushToTalk) {
        btns.push(microphoneBtn);
        btns.push(callBtn);
      } else {
        btns.push(callBtn);
        btns.push(microphoneBtn);
      }
    } else {
      btns.push(callBtn);
      btns.push(microphoneBtn);
      // 对讲机模式，新增占位按钮，让声音按钮在中间
      if (enablePushToTalk) {
        btns.push(emptyBtn);
      }
    }
  } else {
    btns.push(callBtn);
  }

  return (
    <div className='footer'>
      <ul className='_action-list'>{btns.map((btn) => btn)}</ul>
    </div>
  );
}
export default Footer;
