// Web/React/src/AliAIChat/Call/index.vue
<!-- eslint-disable vue/custom-event-name-casing -->
<script lang="ts">
import {
  computed,
  defineComponent,
  onMounted,
  onUnmounted,
  ref,
  watch,
} from 'vue'
import type {
  AICallChatSyncConfig,
} from 'aliyun-auikit-aicall'
import {
  AICallAgentType,
  AICallTemplateConfig,
} from 'aliyun-auikit-aicall'
import { isAndroidWeChatBrowser } from '../common/utils'
import AUIAICallStandardController from '../controller/call/AUIAICallStandardController'
import Stage from './Stage.vue'
import { useCallStore } from './store'
import { ControllerContextKey } from './provider'

export default defineComponent({
  name: 'Call',
  components: {
    Stage,
  },
  props: {
    userId: {
      type: String,
      required: true,
    },
    userToken: {
      type: String,
      required: true,
    },
    agentType: {
      type: String,
      required: true,
    },
    autoCall: {
      type: Boolean,
      default: undefined,
    },
    shareToken: {
      type: String,
      default: undefined,
    },
    fromShare: {
      type: Boolean,
      default: false,
    },
    agentId: {
      type: String,
      default: undefined,
    },
    appServer: {
      type: String,
      required: true,
    },
    region: {
      type: String,
      default: undefined,
    },
    userData: {
      type: String,
      default: undefined,
    },
    templateConfig: {
      type: Object,
      default: undefined,
    },
    chatSyncConfig: {
      type: Object as () => AICallChatSyncConfig,
      default: undefined,
    },
    rtcEngineConfig: {
      type: Object as () => {
        environment?: 'PRE' | 'PROD'
        useAudioPlugin?: boolean
        dumpAudio?: boolean
      },
      default: undefined,
    },
  },
  emits: ['exit', 'auth-fail'],
  setup(props, { emit }) {
    const controllerRef = ref<AUIAICallStandardController | null>(null)

    const shouldAutoCall = computed(() => {
      const urlParams = new URLSearchParams(window.location.search)
      const hasNoCallParam = urlParams.get('nocall') !== null

      if (props.autoCall !== undefined) {
        return props.autoCall
      }

      // 微信安卓端自动播放会失败，分享场景需要手动点击通话
      if (
        hasNoCallParam
        || (controllerRef.value?.config.fromShare && isAndroidWeChatBrowser())
      ) {
        return false
      }

      return true
    })

    const beforeOnload = () => {
      controllerRef.value?.handup()
    }

    onMounted(() => {
      initCall()

      // 关闭页面时尝试挂断，减少出现 Agent 需要超时才能退出的情况
      window.addEventListener('beforeunload', beforeOnload)
    })

    onUnmounted(() => {
      // 清理事件监听
      window.removeEventListener('beforeunload', beforeOnload)

      controllerRef.value?.destroy()
    })

    onMounted(() => {
      initCall()
    })

    async function initCall() {
      const {
        userId,
        userToken,
        shareToken,
        fromShare,
        agentId,
        agentType,
        appServer,
        region,
        userData,
        templateConfig,
        chatSyncConfig,
        rtcEngineConfig,
      } = props

      try {
        if (controllerRef.value) {
          controllerRef.value.destroy()
          controllerRef.value = null
        }

        if (!userId || !userToken)
          return null

        useCallStore().setState({
          agentType: agentType as unknown as AICallAgentType,
        })

        const controller = new AUIAICallStandardController(userId, userToken)

        if (shareToken) {
          controller.shareConfig = shareToken

          if (!controller.shareConfig) {
            ElMessage.error({
              message: '分享链接有误',
            })
            return
          }

          if (controller.shareConfig.templateConfig) {
            controller.config.templateConfig
              = AICallTemplateConfig.fromJsonString(
                controller.shareConfig?.agentType
                || AICallAgentType.VoiceAgent,
                controller.shareConfig?.templateConfig,
              )
          }

          controller.config.fromShare = true
        }
        else {
          controller.config.fromShare = !!fromShare

          if (agentId) {
            controller.config.agentId = agentId
          }

          if (chatSyncConfig) {
            controller.config.chatSyncConfig = chatSyncConfig
          }
        }

        if (appServer)
          controller.appServer = appServer
        if (rtcEngineConfig)
          controller.config.rtcEngineConfig = rtcEngineConfig
        if (region)
          controller.config.region = region
        if (userData) {
          controller.config.userData = userData
        }
        if (templateConfig) {
          controller.config.templateConfig = templateConfig as any
        }

        controllerRef.value = controller
      }
      catch (error) {
        console.error('Failed to initialize call:', error)
      }
    }

    const onExitClick = () => {
      // if (controllerRef.value) {
      //   controllerRef.value.destroy()
      //   controllerRef.value = null
      // }
      emit('exit')
    }

    const onAuthFail = () => {
      emit('auth-fail')
    }

    provide(ControllerContextKey, reactive(controllerRef))

    return {
      controllerRef,
      shouldAutoCall,
      onExitClick,
      onAuthFail,
      agentType: props.agentType as any,
    }
  },
})
</script>

<template>
  <Stage
    :agent-type="agentType"
    :auto-call="shouldAutoCall"
    @auth-fail="onAuthFail"
    @exit="onExitClick"
  />
</template>

<style lang="scss">
  .call-container {
  position: relative;
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
  overflow: hidden;
  background-color: #000;
}
</style>

// Web/React/src/Mobile/Call/index.tsx
import { useEffect, useMemo } from 'react';
import {
  AICallAgentType,
  AICallChatSyncConfig,
  AICallTemplateConfig,
} from 'aliyun-auikit-aicall';
import AUIAICallStandardController from '@/controller/call/AUIAICallStandardController';

import './index.less';
import useCallStore from './store';
import { Toast } from 'antd-mobile';
import ControllerContext from './ControlerContext';
import Stage from './Stage';
import { isAndroidWeChatBrowser } from '@/common/utils';

export interface CallProps {
  agentType: AICallAgentType;
  userId?: string;
  userToken?: string;
  autoCall?: boolean;

  shareToken?: string;
  fromShare?: boolean;

  agentId?: string;
  appServer?: string;
  region?: string;
  userData?: string;
  templateConfig?: AICallTemplateConfig;
  isShare?: boolean;
  onExit?: () => void;
  onAuthFail?: () => void;
  chatSyncConfig?: AICallChatSyncConfig;
  rtcEngineConfig?: {
    environment?: 'PRE' | 'PROD';
    useAudioPlugin?: boolean;
    dumpAudio?: boolean;
  };
  children?: React.ReactNode;
}

function Call({
  userId,
  userToken,
  agentId,
  autoCall,
  shareToken,
  fromShare,
  appServer,
  region,
  agentType,
  userData,
  templateConfig,
  onExit,
  onAuthFail,
  chatSyncConfig,
  rtcEngineConfig,
  children,
}: CallProps) {
  const controller = useMemo(() => {
    if (!userId || !userToken) return null;
    useCallStore.setState({
      agentType,
    });
    const _controller = new AUIAICallStandardController(userId, userToken);
    if (appServer) _controller.appServer = appServer;

    if (shareToken) {
      _controller.shareConfig = shareToken;

      if (!_controller.shareConfig) {
        Toast.show({
          content: '分享链接有误',
          position: 'bottom',
        });
        return null;
      }
      if (_controller.shareConfig.templateConfig) {
        _controller.config.templateConfig = AICallTemplateConfig.fromJsonString(
          _controller.shareConfig?.agentType || AICallAgentType.VoiceAgent,
          _controller.shareConfig?.templateConfig,
        );
      }
      _controller.config.fromShare = true;
    } else {
      _controller.config.fromShare = !!fromShare;
      if (agentId) {
        _controller.config.agentId = agentId;
      }
      if (chatSyncConfig) {
        _controller.config.chatSyncConfig = chatSyncConfig;
      }
    }

    if (appServer) _controller.appServer = appServer;
    if (rtcEngineConfig) _controller.config.rtcEngineConfig = rtcEngineConfig;
    if (region) _controller.config.region = region;
    if (userData) {
      _controller.config.userData = userData;
    }
    if (templateConfig) {
      _controller.config.templateConfig = templateConfig;
    }

    return _controller;
  }, [
    userId,
    userToken,
    shareToken,
    fromShare,
    appServer,
    region,
    agentId,
    userData,
    templateConfig,
    agentType,
    chatSyncConfig,
  ]);

  // 关闭页面时尝试挂断，减少出现 Agent 需要超时才能退出的 Case
  useEffect(() => {
    const beforeOnload = () => {
      controller?.handup();
    };
    window.addEventListener('beforeunload', beforeOnload);
    return () => {
      window.removeEventListener('beforeunload', beforeOnload);
    };
  }, []);

  return (
    <ControllerContext.Provider value={controller}>
      <Stage
        // 微信安卓端自动播放会失败，分享场景需要手动点击通话
        agentType={agentType}
        autoCall={
          autoCall ||
          (new URLSearchParams(location.search).get('nocall') ||
          (controller?.config.fromShare && isAndroidWeChatBrowser())
            ? false
            : true)
        }
        onAuthFail={() => {
          onAuthFail?.();
        }}
        onExit={() => {
          onExit?.();
        }}
      />
      {children}
    </ControllerContext.Provider>
  );
}

export default Call;
