// Web/React/src/VueMobile/Call/index.vue
<template>
  <div class="call-container" :style="containerStyle">
    <controller-context-provider :value="controllerRef">
      <Stage
        :agent-type="agentType"
        :auto-call="shouldAutoCall"
        @auth-fail="onAuthFail"
        @exit="onExitClick"
      />
      <slot></slot>
    </controller-context-provider>
  </div>
</template>

<script lang="ts">
  import {
    computed,
    defineComponent,
    onMounted,
    onUnmounted,
    ref,
    watch,
  } from 'vue';
  import {
    AICallController,
    AICallOptions,
    AICallAgentType,
    AICallTemplateConfig,
    AICallChatSyncConfig,
  } from 'aliyun-auikit-aicall';
  import { Toast } from 'vant';
  import Stage from './Stage.vue';
  import ControllerContextProvider from './ControlerContext';
  import { defaultCallBehavior } from './store';
  import { isAndroidWeChatBrowser } from '../../common/utils';

  export default defineComponent({
    name: 'Call',
    components: {
      Stage,
      ControllerContextProvider,
    },
    props: {
      userId: {
        type: String,
        required: true,
      },
      userToken: {
        type: String,
        required: true,
      },
      agentType: {
        type: String,
        required: true,
      },
      autoCall: {
        type: Boolean,
        default: undefined,
      },
      shareToken: {
        type: String,
        default: undefined,
      },
      fromShare: {
        type: Boolean,
        default: false,
      },
      agentId: {
        type: String,
        default: undefined,
      },
      appServer: {
        type: String,
        required: true,
      },
      region: {
        type: String,
        default: undefined,
      },
      userData: {
        type: String,
        default: undefined,
      },
      templateConfig: {
        type: Object,
        default: undefined,
      },
      chatSyncConfig: {
        type: Object as () => AICallChatSyncConfig,
        default: undefined,
      },
      rtcEngineConfig: {
        type: Object as () => {
          environment?: 'PRE' | 'PROD';
          useAudioPlugin?: boolean;
          dumpAudio?: boolean;
        },
        default: undefined,
      },
    },
    emits: ['exit', 'auth-fail'],
    setup(props, { emit }) {
      const controllerRef = ref<AICallController | null>(null);

      const containerStyle = computed(() => ({
        '--aicall-safe-area-top': '0px',
        '--aicall-safe-area-bottom': '0px',
      }));

      // 计算是否应该自动拨号
      const shouldAutoCall = computed(() => {
        const urlParams = new URLSearchParams(window.location.search);
        const hasNoCallParam = urlParams.get('nocall') !== null;

        // 优先使用props中的autoCall
        if (props.autoCall !== undefined) {
          return props.autoCall;
        }

        // 微信安卓端自动播放会失败，分享场景需要手动点击通话
        if (
          hasNoCallParam ||
          (controllerRef.value?.config.fromShare && isAndroidWeChatBrowser())
        ) {
          return false;
        }

        return true;
      });

      onMounted(() => {
        initCall();

        // 关闭页面时尝试挂断，减少出现 Agent 需要超时才能退出的情况
        const beforeOnload = () => {
          controllerRef.value?.handup();
        };
        window.addEventListener('beforeunload', beforeOnload);
      });

      onUnmounted(() => {
        // 清理事件监听
        window.removeEventListener('beforeunload', () => {
          controllerRef.value?.handup();
        });

        controllerRef.value?.destroy();
      });

      watch(
        () => props,
        () => {
          initCall();
        },
        { deep: true },
      );

      const initCall = async () => {
        const {
          userId,
          userToken,
          agentType,
          shareToken,
          fromShare,
          agentId,
          appServer,
          region,
          userData,
          templateConfig,
          chatSyncConfig,
          rtcEngineConfig,
        } = props;

        try {
          if (controllerRef.value) {
            controllerRef.value.destroy();
            controllerRef.value = null;
          }

          const options: AICallOptions = {
            userId,
            userToken,
            agentId,
            appServer,
            region,
            userData,
            templateConfig,
            behavior: defaultCallBehavior,
            onAuthFail: () => {
              emit('auth-fail');
            },
          };

          const controller = new AICallController(options);

          // 处理分享相关配置
          if (shareToken) {
            controller.shareConfig = shareToken;

            if (!controller.shareConfig) {
              Toast({
                message: '分享链接有误',
                position: 'bottom',
              });
              return;
            }

            if (controller.shareConfig.templateConfig) {
              controller.config.templateConfig =
                AICallTemplateConfig.fromJsonString(
                  controller.shareConfig?.agentType ||
                    AICallAgentType.VoiceAgent,
                  controller.shareConfig?.templateConfig,
                );
            }

            controller.config.fromShare = true;
          } else {
            controller.config.fromShare = !!fromShare;

            if (agentId) {
              controller.config.agentId = agentId;
            }

            if (chatSyncConfig) {
              controller.config.chatSyncConfig = chatSyncConfig;
            }
          }

          // 设置RTC引擎配置
          if (rtcEngineConfig) {
            controller.config.rtcEngineConfig = rtcEngineConfig;
          }

          controllerRef.value = controller;
        } catch (error) {
          console.error('Failed to initialize call:', error);
        }
      };

      const onExitClick = () => {
        if (controllerRef.value) {
          controllerRef.value.destroy();
          controllerRef.value = null;
        }
        emit('exit');
      };

      const onAuthFail = () => {
        emit('auth-fail');
      };

      return {
        controllerRef,
        containerStyle,
        shouldAutoCall,
        onExitClick,
        onAuthFail,
        agentType,
      };
    },
  });
</script>

<style lang="less">
  .call-container {
    position: relative;
    display: flex;
    flex-direction: column;
    height: 100vh;
    width: 100%;
    overflow: hidden;
    background-color: #000;
  }
</style>

// Web/React/src/Mobile/Call/index.tsx
import { useEffect, useMemo } from 'react';
import {
  AICallAgentType,
  AICallChatSyncConfig,
  AICallTemplateConfig,
} from 'aliyun-auikit-aicall';
import AUIAICallStandardController from '@/controller/call/AUIAICallStandardController';

import './index.less';
import useCallStore from './store';
import { Toast } from 'antd-mobile';
import ControllerContext from './ControlerContext';
import Stage from './Stage';
import { isAndroidWeChatBrowser } from '@/common/utils';

export interface CallProps {
  agentType: AICallAgentType;
  userId?: string;
  userToken?: string;
  autoCall?: boolean;

  shareToken?: string;
  fromShare?: boolean;

  agentId?: string;
  appServer?: string;
  region?: string;
  userData?: string;
  templateConfig?: AICallTemplateConfig;
  isShare?: boolean;
  onExit?: () => void;
  onAuthFail?: () => void;
  chatSyncConfig?: AICallChatSyncConfig;
  rtcEngineConfig?: {
    environment?: 'PRE' | 'PROD';
    useAudioPlugin?: boolean;
    dumpAudio?: boolean;
  };
  children?: React.ReactNode;
}

function Call({
  userId,
  userToken,
  agentId,
  autoCall,
  shareToken,
  fromShare,
  appServer,
  region,
  agentType,
  userData,
  templateConfig,
  onExit,
  onAuthFail,
  chatSyncConfig,
  rtcEngineConfig,
  children,
}: CallProps) {
  const controller = useMemo(() => {
    if (!userId || !userToken) return null;
    useCallStore.setState({
      agentType,
    });
    const _controller = new AUIAICallStandardController(userId, userToken);
    if (appServer) _controller.appServer = appServer;

    if (shareToken) {
      _controller.shareConfig = shareToken;

      if (!_controller.shareConfig) {
        Toast.show({
          content: '分享链接有误',
          position: 'bottom',
        });
        return null;
      }
      if (_controller.shareConfig.templateConfig) {
        _controller.config.templateConfig = AICallTemplateConfig.fromJsonString(
          _controller.shareConfig?.agentType || AICallAgentType.VoiceAgent,
          _controller.shareConfig?.templateConfig,
        );
      }
      _controller.config.fromShare = true;
    } else {
      _controller.config.fromShare = !!fromShare;
      if (agentId) {
        _controller.config.agentId = agentId;
      }
      if (chatSyncConfig) {
        _controller.config.chatSyncConfig = chatSyncConfig;
      }
    }

    if (appServer) _controller.appServer = appServer;
    if (rtcEngineConfig) _controller.config.rtcEngineConfig = rtcEngineConfig;
    if (region) _controller.config.region = region;
    if (userData) {
      _controller.config.userData = userData;
    }
    if (templateConfig) {
      _controller.config.templateConfig = templateConfig;
    }

    return _controller;
  }, [
    userId,
    userToken,
    shareToken,
    fromShare,
    appServer,
    region,
    agentId,
    userData,
    templateConfig,
    agentType,
    chatSyncConfig,
  ]);

  // 关闭页面时尝试挂断，减少出现 Agent 需要超时才能退出的 Case
  useEffect(() => {
    const beforeOnload = () => {
      controller?.handup();
    };
    window.addEventListener('beforeunload', beforeOnload);
    return () => {
      window.removeEventListener('beforeunload', beforeOnload);
    };
  }, []);

  return (
    <ControllerContext.Provider value={controller}>
      <Stage
        // 微信安卓端自动播放会失败，分享场景需要手动点击通话
        agentType={agentType}
        autoCall={
          autoCall ||
          (new URLSearchParams(location.search).get('nocall') ||
          (controller?.config.fromShare && isAndroidWeChatBrowser())
            ? false
            : true)
        }
        onAuthFail={() => {
          onAuthFail?.();
        }}
        onExit={() => {
          onExit?.();
        }}
      />
      {children}
    </ControllerContext.Provider>
  );
}

export default Call;
